-- Construction du DWH dans le schema "dwh" de la base "peche_nc"
-- depuis l'ODS "env_mer".
-- Constellation : 4 tables de faits, 11 dimensions, 2 tables de pont.
-- Chaque dimension porte une cle de substitution et un membre inconnu de
-- cle -1 : aucun NULL en cle etrangere, aucune jointure ne perd de lignes.
--
-- PORTEE : ce script INITIALISE le DWH. Il reconstruit tout a chaque
-- execution et ne conserve donc aucun historique : ni date d'integration, ni
-- distinction entre lignes nouvelles, modifiees et inchangees. L'alimentation
-- incrementale prevue par le SFD reste a ecrire ; ne pas utiliser ce script
-- pour les chargements courants.
--
-- HYPOTHESE SUR LE RATTACHEMENT AU NAVIRE
-- Les faits portent un navire_key derive de
-- pecheur_anonymise.carte_autorisation_navire_id. Cette colonne designe le
-- navire AUTORISE SUR LA CARTE, et non celui qui a reellement effectue la
-- campagne : le SFD constate qu'aucune relation fiable entre pecheurs et
-- navires n'existe dans les sources, et met hors perimetre V1 les indicateurs
-- qui en dependent (frais d'entretien par navire, navires par pecheur,
-- rentabilite par navire).
-- L'axe est conserve ici pour ne pas perdre l'information, mais il est
-- INDICATIF. Toute restitution par navire doit rappeler cette limite, et
-- aucun indicateur du SFD ne doit s'appuyer dessus sans validation metier.


-- 0. SCHEMA ET REMISE A ZERO -------------------------------------------------

-- Le script doit etre execute en etant connecte a la base peche_nc.
CREATE SCHEMA IF NOT EXISTS dwh;
SET search_path TO dwh, public;

-- Ordre inverse des dependances.
DROP TABLE IF EXISTS PONT_CAPTURE_ZONE;
DROP TABLE IF EXISTS PONT_CARTE_PECHERIE;
DROP TABLE IF EXISTS FAIT_FRAIS;
DROP TABLE IF EXISTS FAIT_CAPTURE;
DROP TABLE IF EXISTS FAIT_CAMPAGNE;
DROP TABLE IF EXISTS FAIT_CARTE;
DROP TABLE IF EXISTS DIM_CARROYAGE;
DROP TABLE IF EXISTS DIM_ZONE_PECHE;
DROP TABLE IF EXISTS DIM_PECHERIE;
DROP TABLE IF EXISTS DIM_TECHNIQUE;
DROP TABLE IF EXISTS DIM_ESPECE;
DROP TABLE IF EXISTS DIM_MOTEUR;
DROP TABLE IF EXISTS DIM_NAVIRE;
DROP TABLE IF EXISTS DIM_CARTE;
DROP TABLE IF EXISTS DIM_COMMUNE;
DROP TABLE IF EXISTS DIM_PERSONNE;
DROP TABLE IF EXISTS DIM_TEMPS;


-- 1. DIMENSIONS --------------------------------------------------------------

-- Calendrier genere, pas deduit des dates observees : sinon les jours sans
-- activite manquent et le cumul glissant devient impossible. Cle AAAAMMJJ.
CREATE TABLE DIM_TEMPS (
    temps_key    INT         NOT NULL PRIMARY KEY,
    date_id      DATE        NULL,
    jour         SMALLINT    NULL,
    mois         SMALLINT    NULL,
    trimestre    SMALLINT    NULL,
    annee        SMALLINT    NULL,
    libelle_mois VARCHAR(20) NULL,
    jour_semaine VARCHAR(20) NULL,
    saison       VARCHAR(20) NULL
);

INSERT INTO DIM_TEMPS (temps_key, date_id, jour, mois, trimestre, annee,
                       libelle_mois, jour_semaine, saison)
VALUES (-1, NULL, NULL, NULL, NULL, NULL, 'Inconnu', 'Inconnu', 'Inconnu');

INSERT INTO DIM_TEMPS (temps_key, date_id, jour, mois, trimestre, annee,
                       libelle_mois, jour_semaine, saison)
SELECT TO_CHAR(d, 'YYYYMMDD')::INT, d,
       EXTRACT(DAY FROM d)::SMALLINT,
       EXTRACT(MONTH FROM d)::SMALLINT,
       EXTRACT(QUARTER FROM d)::SMALLINT,
       EXTRACT(YEAR FROM d)::SMALLINT,
       TO_CHAR(d, 'TMMonth'), TO_CHAR(d, 'TMDay'),
       CASE WHEN EXTRACT(MONTH FROM d)::INT IN (12,1,2) THEN 'Été'     -- hemisphere sud
            WHEN EXTRACT(MONTH FROM d)::INT IN (3,4,5)  THEN 'Automne'
            WHEN EXTRACT(MONTH FROM d)::INT IN (6,7,8)  THEN 'Hiver'
            ELSE 'Printemps' END
FROM GENERATE_SERIES(DATE '1990-01-01', DATE '2030-12-31', INTERVAL '1 day') AS jours(d);


CREATE TABLE DIM_COMMUNE (
    commune_key INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    commune     VARCHAR(200) NULL
);

INSERT INTO DIM_COMMUNE (commune_key, commune) VALUES (-1, 'Non renseignée');

-- La commune apparait dans trois colonnes sources.
INSERT INTO DIM_COMMUNE (commune)
SELECT DISTINCT BTRIM(c)
FROM (
    SELECT capitaine_commune AS c FROM env_mer.pecheur_anonymise
    UNION SELECT patron_pecheur_commune FROM env_mer.pecheur_anonymise
    UNION SELECT carte_autorisation_commune FROM env_mer.pecheur_anonymise
) AS x
WHERE c IS NOT NULL AND BTRIM(c) <> '';


-- Capitaines et patrons fusionnes, UNE SEULE LIGNE PAR PERSONNE.
-- Le grain doit etre strictement la personne : les faits joignent sur
-- personne_id, et un doublon y ferait enfler la jointure jusqu'a violer la
-- cle primaire de FAIT_CARTE. Grouper sur la commune produisait ce doublon
-- pour les 3 personnes dont la commune varie d'un role a l'autre ; la
-- commune est donc agregee comme les autres attributs.
CREATE TABLE DIM_PERSONNE (
    personne_key    INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    personne_id     VARCHAR(255) NULL,
    commune_key     INT          NOT NULL,
    date_naissance  DATE         NULL,
    annee_naissance SMALLINT     NULL,
    sexe            VARCHAR(60)  NULL,
    est_capitaine   BOOLEAN      NOT NULL,
    est_patron      BOOLEAN      NOT NULL
);

INSERT INTO DIM_PERSONNE (personne_key, personne_id, commune_key,
                          date_naissance, annee_naissance, sexe,
                          est_capitaine, est_patron)
VALUES (-1, NULL, -1, NULL, NULL, 'Inconnu', FALSE, FALSE);

WITH roles AS (
    SELECT capitaine_id AS personne_id, capitaine_commune AS commune,
           capitaine_date_naissance AS naissance, capitaine_sexe AS sexe,
           1 AS capitaine, 0 AS patron
    FROM env_mer.pecheur_anonymise
    WHERE capitaine_id IS NOT NULL
    UNION ALL
    SELECT patron_pecheur_id, patron_pecheur_commune,
           patron_pecheur_date_naissance, patron_pecheur_sexe, 0, 1
    FROM env_mer.pecheur_anonymise
    WHERE patron_pecheur_id IS NOT NULL
)
INSERT INTO DIM_PERSONNE (personne_id, commune_key, date_naissance,
                          annee_naissance, sexe, est_capitaine, est_patron)
SELECT r.personne_id,
       MAX(COALESCE(dc.commune_key, -1)),
       MAX(r.naissance),
       CASE WHEN EXTRACT(YEAR FROM MAX(r.naissance)) BETWEEN 1900 AND 2030
            THEN EXTRACT(YEAR FROM MAX(r.naissance))::SMALLINT END,
       MAX(r.sexe),
       MAX(r.capitaine) = 1, MAX(r.patron) = 1
FROM roles r
LEFT JOIN DIM_COMMUNE dc ON dc.commune = BTRIM(r.commune)
GROUP BY r.personne_id;


CREATE TABLE DIM_CARTE (
    carte_key                   INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    carte_id                    VARCHAR(255) NULL,
    carte_type                  VARCHAR(120) NULL,
    carte_type_source           VARCHAR(120) NULL,
    carte_annee                 VARCHAR(20)  NULL,
    carte_renouvellement        BOOLEAN      NULL,
    carte_autorisation_statut   VARCHAR(120) NULL,
    carte_autorisation_annee    VARCHAR(20)  NULL,
    commune_key                 INT          NOT NULL,
    carte_autorisation_province VARCHAR(120) NULL
);

INSERT INTO DIM_CARTE (carte_key, carte_id, carte_type, carte_type_source,
                       commune_key)
VALUES (-1, NULL, 'Inconnu', NULL, -1);

-- La source porte cinq orthographes pour deux types de carte, dont une
-- doublement encodee. On normalise et on garde la variante brute.
INSERT INTO DIM_CARTE (carte_id, carte_type, carte_type_source, carte_annee,
                       carte_renouvellement, carte_autorisation_statut,
                       carte_autorisation_annee, commune_key,
                       carte_autorisation_province)
SELECT p.carte_id,
       CASE
         WHEN p.carte_type LIKE 'C%ti%re' OR p.carte_type LIKE 'C%tiere' THEN 'Côtière'
         WHEN p.carte_type LIKE 'Ha%ri%re' OR p.carte_type LIKE 'Haut%'  THEN 'Hauturière'
         ELSE p.carte_type
       END,
       p.carte_type,
       p.carte_annee, p.carte_renouvellement, p.carte_autorisation_statut,
       p.carte_autorisation_annee,
       COALESCE(dc.commune_key, -1),
       p.carte_autorisation_province
FROM env_mer.pecheur_anonymise p
LEFT JOIN DIM_COMMUNE dc
       ON dc.commune = BTRIM(p.carte_autorisation_commune);


-- nb_moteurs est un attribut legitime du navire. Le detail des moteurs vit
-- dans DIM_MOTEUR : 24 navires en portent plusieurs, et retenir MAX(marque)
-- et MAX(carburant) independamment pouvait produire un couple qui n'existe
-- dans aucun moteur reel.
CREATE TABLE DIM_NAVIRE (
    navire_key            INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    navire_id             VARCHAR(255) NULL,
    annee_construction    INT          NULL,
    longueur              DOUBLE PRECISION NULL,
    tranche_longueur      VARCHAR(30)  NULL,
    jauge_brute           DOUBLE PRECISION NULL,
    origine               VARCHAR(120) NULL,
    categorie_navigation  VARCHAR(120) NULL,
    materiau              VARCHAR(120) NULL,
    constructeur          VARCHAR(200) NULL,
    nb_moteurs            INT          NULL
);

INSERT INTO DIM_NAVIRE (navire_key, navire_id, tranche_longueur, nb_moteurs)
VALUES (-1, NULL, 'Inconnue', 0);

INSERT INTO DIM_NAVIRE (navire_id, annee_construction, longueur,
                        tranche_longueur, jauge_brute, origine,
                        categorie_navigation, materiau, constructeur,
                        nb_moteurs)
SELECT n.navire_id,
       CASE
         WHEN BTRIM(n.navire_annee_construction) ~ '^[+-]?[0-9]+$' THEN
           CASE
             WHEN BTRIM(n.navire_annee_construction)::NUMERIC BETWEEN -2147483648 AND 2147483647
             THEN BTRIM(n.navire_annee_construction)::INT
             ELSE NULL
           END
         ELSE NULL
       END,  -- equivalent TRY_CONVERT(INT, ...)
       CASE WHEN n.navire_longueur > 0 THEN n.navire_longueur END,
       CASE WHEN n.navire_longueur IS NULL OR n.navire_longueur <= 0 THEN 'Inconnue'
            WHEN n.navire_longueur <  6 THEN 'Moins de 6 m'
            WHEN n.navire_longueur < 10 THEN '6 à 10 m'
            WHEN n.navire_longueur < 15 THEN '10 à 15 m'
            ELSE '15 m et plus' END,
       CASE WHEN n.navire_jauge_brute > 0 THEN n.navire_jauge_brute END,
       n.navire_origine, n.categorie_navigation, n.materiau, n.constructeur,
       COALESCE(m.nb, 0)
FROM env_mer.navire_peche_anonymise n
LEFT JOIN (
    SELECT navire_id, COUNT(*) AS nb
    FROM env_mer.navire_moteur
    GROUP BY navire_id
) m ON m.navire_id = n.navire_id;


-- Un moteur appartient a un seul navire : la relation est 1-N, une table de
-- pont serait inutile. Le couple marque/carburant reste ici celui d'un moteur
-- reel, jamais une recomposition.
CREATE TABLE DIM_MOTEUR (
    moteur_key   INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    moteur_id    VARCHAR(255) NULL,
    navire_key   INT          NOT NULL,
    usage_moteur VARCHAR(200) NULL,
    marque       VARCHAR(200) NULL,
    carburant    VARCHAR(60)  NULL
);

INSERT INTO DIM_MOTEUR (moteur_key, moteur_id, navire_key, usage_moteur,
                        marque, carburant)
VALUES (-1, NULL, -1, 'Inconnu', 'Inconnue', 'Inconnu');

INSERT INTO DIM_MOTEUR (moteur_id, navire_key, usage_moteur, marque, carburant)
SELECT m.moteur_id, COALESCE(n.navire_key, -1),
       LEFT(m.usage, 200), LEFT(m.marque, 200), LEFT(m.carburant, 60)
FROM env_mer.navire_moteur m
LEFT JOIN DIM_NAVIRE n ON n.navire_id = m.navire_id;


-- Cle de substitution : une PK (categorie_code, produit) porterait sur du
-- NVARCHAR long, au-dela des 900 octets admis pour une cle d'index.
CREATE TABLE DIM_ESPECE (
    espece_key      INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    categorie_code  VARCHAR(255) NULL,
    categorie_nom   VARCHAR(255) NULL,
    produit         VARCHAR(400) NULL,
    seuil_fiab70    DOUBLE PRECISION NULL,
    seuil_fiab95    DOUBLE PRECISION NULL
);

INSERT INTO DIM_ESPECE (espece_key, categorie_nom, produit)
VALUES (-1, 'Inconnue', 'Inconnu');

INSERT INTO DIM_ESPECE (categorie_code, categorie_nom, produit,
                        seuil_fiab70, seuil_fiab95)
SELECT capture_categorie_code,
       MAX(capture_categorie_nom),
       LEFT(capture_produit, 400),
       MAX(capture_categorie_seuil_fiabilite70),
       MAX(capture_categorie_seuil_fiabilite95)
FROM env_mer.capture_peche
WHERE capture_categorie_code IS NOT NULL
GROUP BY capture_categorie_code, LEFT(capture_produit, 400);


-- Grain : le couple (technique, transformation). Joindre sur la seule
-- technique multiplierait les lignes du fait, d'ou la cle de substitution.
CREATE TABLE DIM_TECHNIQUE (
    technique_key  INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    technique      VARCHAR(200) NULL,
    transformation VARCHAR(200) NULL
);

INSERT INTO DIM_TECHNIQUE (technique_key, technique, transformation)
VALUES (-1, 'Inconnue', 'Inconnue');

INSERT INTO DIM_TECHNIQUE (technique, transformation)
SELECT DISTINCT LEFT(capture_technique, 200), LEFT(capture_transformation, 200)
FROM env_mer.capture_peche
WHERE capture_technique IS NOT NULL OR capture_transformation IS NOT NULL;


-- Aucun referentiel de zones dans l'ODS : reconstruit depuis capture_zone,
-- commune et superficie venant du carroyage.
CREATE TABLE DIM_ZONE_PECHE (
    zone_key       INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    zone_peche_id  VARCHAR(255) NULL,
    label          VARCHAR(400) NULL,
    communes       VARCHAR(500) NULL,
    superficie_km2 DOUBLE PRECISION NULL
);

INSERT INTO DIM_ZONE_PECHE (zone_key, zone_peche_id, label)
VALUES (-1, NULL, 'Zone inconnue');

INSERT INTO DIM_ZONE_PECHE (zone_peche_id, label, communes, superficie_km2)
SELECT z.zone_peche_id, MAX(z.label),
       (SELECT STRING_AGG(CAST(c.carroyage_commune AS VARCHAR(100)), ', ')
        FROM env_mer.carroyage_peche c
        WHERE c.coarroyage_zone_peche_id = z.zone_peche_id),
       (SELECT SUM(c.carroyage_superficie_nv_carroyage_km2)
        FROM env_mer.carroyage_peche c
        WHERE c.coarroyage_zone_peche_id = z.zone_peche_id)
FROM env_mer.capture_zone z
WHERE z.zone_peche_id IS NOT NULL
GROUP BY z.zone_peche_id;


CREATE TABLE DIM_CARROYAGE (
    carroyage_key         INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    carroyage_id          INT          NULL,
    commune               VARCHAR(50) NULL,
    eth                   VARCHAR(50) NULL,
    zone_ancienne         VARCHAR(50) NULL,
    zone_nouvelle         VARCHAR(50) NULL,
    zone_peche_id_associe VARCHAR(255) NULL,
    zone_key              INT          NOT NULL,
    superficie_km2        DOUBLE PRECISION NULL
);

INSERT INTO DIM_CARROYAGE (carroyage_id, commune, eth, zone_ancienne,
                           zone_nouvelle, zone_peche_id_associe, zone_key,
                           superficie_km2)
SELECT c.carroyage_id, c.carroyage_commune, c.carroyage_eth,
       c.carroyage_zone_peche, c.carroyage_nouvelle_zone_peche,
       c.coarroyage_zone_peche_id,
       COALESCE(z.zone_key, -1),
       c.carroyage_superficie_nv_carroyage_km2
FROM env_mer.carroyage_peche c
LEFT JOIN DIM_ZONE_PECHE z ON z.zone_peche_id = c.coarroyage_zone_peche_id;


CREATE TABLE DIM_PECHERIE (
    pecherie_key INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    code         VARCHAR(60)  NULL,
    nom          VARCHAR(400) NULL,
    zone         VARCHAR(200) NULL,
    taille_mini  VARCHAR(120) NULL,
    periode      VARCHAR(200) NULL,
    quota        VARCHAR(200) NULL
);

INSERT INTO DIM_PECHERIE (pecherie_key, code, nom) VALUES (-1, NULL, 'Inconnue');

INSERT INTO DIM_PECHERIE (code, nom, zone, taille_mini, periode, quota)
SELECT code, MAX(BTRIM(nom)), MAX(zone), MAX(taille),
       MAX(periode), MAX(quantite)
FROM env_mer.carte_pecherie_specifique
WHERE code IS NOT NULL
GROUP BY code;


-- 2. TABLES DE FAITS ---------------------------------------------------------

-- Grain : une carte de peche.
-- AGREGAT : ses mesures somment les campagnes de la carte. Ne jamais
-- additionner FAIT_CARTE.carte_recette et FAIT_CAMPAGNE.campagne_recette.
CREATE TABLE FAIT_CARTE (
    carte_id             VARCHAR(255) NOT NULL PRIMARY KEY,
    carte_key            INT NOT NULL,
    temps_key            INT NOT NULL,
    capitaine_key        INT NOT NULL,
    patron_key           INT NOT NULL,
    navire_key           INT NOT NULL,
    commune_key          INT NOT NULL,
    carte_benefice       DOUBLE PRECISION NULL,
    carte_depense        DOUBLE PRECISION NULL,
    carte_recette        DOUBLE PRECISION NULL,
    carte_rendement      DOUBLE PRECISION NULL,
    carte_carburant_qte  DOUBLE PRECISION NULL,
    carte_maree          INT   NULL,
    carte_tonnage_epe    DOUBLE PRECISION NULL
);

INSERT INTO FAIT_CARTE (carte_id, carte_key, temps_key, capitaine_key,
                        patron_key, navire_key, commune_key,
                        carte_benefice, carte_depense, carte_recette,
                        carte_rendement, carte_carburant_qte, carte_maree,
                        carte_tonnage_epe)
SELECT p.carte_id,
       COALESCE(dc.carte_key, -1),
       -- hors des bornes du calendrier : membre inconnu
       CASE WHEN p.carte_date_delivrance IS NOT NULL
             AND EXTRACT(YEAR FROM p.carte_date_delivrance) BETWEEN 1990 AND 2030
            THEN TO_CHAR(p.carte_date_delivrance, 'YYYYMMDD')::INT
            ELSE -1 END,
       COALESCE(cap.personne_key, -1),
       COALESCE(pat.personne_key, -1),
       COALESCE(dn.navire_key, -1),
       COALESCE(dcom.commune_key, -1),
       p.carte_benefice, p.carte_depense, p.carte_recette, p.carte_rendement,
       p.carte_carburant_qte,
       CASE WHEN p.carte_maree >= 0 THEN p.carte_maree END,
       p.carte_tonnage_epe
FROM env_mer.pecheur_anonymise p
LEFT JOIN DIM_CARTE    dc  ON dc.carte_id  = p.carte_id
LEFT JOIN DIM_PERSONNE cap ON cap.personne_id = p.capitaine_id
LEFT JOIN DIM_PERSONNE pat ON pat.personne_id = p.patron_pecheur_id
LEFT JOIN DIM_NAVIRE   dn  ON dn.navire_id = p.carte_autorisation_navire_id
LEFT JOIN DIM_COMMUNE  dcom ON dcom.commune = BTRIM(p.capitaine_commune);


-- Grain : une campagne.
CREATE TABLE FAIT_CAMPAGNE (
    campagne_id               VARCHAR(255) NOT NULL PRIMARY KEY,
    carte_key                 INT NOT NULL,
    navire_key                INT NOT NULL,
    temps_debut_key           INT NOT NULL,
    temps_fin_key             INT NOT NULL,
    duree_jours               INT   NULL,
    campagne_benefice         DOUBLE PRECISION NULL,
    campagne_depense          DOUBLE PRECISION NULL,
    campagne_recette          DOUBLE PRECISION NULL,
    campagne_rendement        DOUBLE PRECISION NULL,
    campagne_carburant_qte    DOUBLE PRECISION NULL,
    campagne_charges_sociales DOUBLE PRECISION NULL,
    campagne_jours_mer        DOUBLE PRECISION NULL,
    campagne_jours_peche      DOUBLE PRECISION NULL,
    campagne_nbre_equipage    DOUBLE PRECISION NULL,
    campagne_nbr_femme_abord  INT   NULL,
    campagne_salaire_matelots DOUBLE PRECISION NULL,
    campagne_salaire_patron   DOUBLE PRECISION NULL,
    campagne_tonnage_epe      DOUBLE PRECISION NULL
);

INSERT INTO FAIT_CAMPAGNE (campagne_id, carte_key, navire_key,
                           temps_debut_key, temps_fin_key, duree_jours,
                           campagne_benefice, campagne_depense,
                           campagne_recette, campagne_rendement,
                           campagne_carburant_qte, campagne_charges_sociales,
                           campagne_jours_mer, campagne_jours_peche,
                           campagne_nbre_equipage, campagne_nbr_femme_abord,
                           campagne_salaire_matelots, campagne_salaire_patron,
                           campagne_tonnage_epe)
SELECT c.campagne_id,
       COALESCE(dc.carte_key, -1),
       COALESCE(fc.navire_key, -1),
       CASE WHEN c.campagne_date_debut IS NOT NULL
             AND EXTRACT(YEAR FROM c.campagne_date_debut) BETWEEN 1990 AND 2030
            THEN TO_CHAR(c.campagne_date_debut, 'YYYYMMDD')::INT
            ELSE -1 END,
       CASE WHEN c.campagne_date_fin IS NOT NULL
             AND EXTRACT(YEAR FROM c.campagne_date_fin) BETWEEN 1990 AND 2030
            THEN TO_CHAR(c.campagne_date_fin, 'YYYYMMDD')::INT
            ELSE -1 END,
       -- duree NULL si la fin precede le debut, plutot qu'une valeur negative
       CASE WHEN c.campagne_date_fin IS NULL OR c.campagne_date_debut IS NULL
            THEN NULL
            WHEN c.campagne_date_fin < c.campagne_date_debut THEN NULL
            ELSE c.campagne_date_fin - c.campagne_date_debut
       END,
       c.campagne_benefice, c.campagne_depense, c.campagne_recette,
       c.campagne_rendement, c.campagne_carburant_qte,
       c.campagne_charges_sociales, c.campagne_jours_mer,
       c.campagne_jours_peche, c.campagne_nbre_equipage,
       c.campagne_nbr_femme_abord, c.campagne_salaire_matelots,
       c.campagne_salaire_patron, c.campagne_tonnage_epe
FROM env_mer.campagne_peche c
LEFT JOIN DIM_CARTE  dc ON dc.carte_id = c.campagne_carte_id
LEFT JOIN FAIT_CARTE fc ON fc.carte_id = c.campagne_carte_id;


-- Grain : une espece capturee. La zone n'y figure pas : une capture en porte
-- jusqu'a 6, l'ajouter multiplierait le poids. Voir PONT_CAPTURE_ZONE.
CREATE TABLE FAIT_CAPTURE (
    capture_id                 VARCHAR(255) NOT NULL PRIMARY KEY,
    campagne_id                VARCHAR(255) NULL,   -- dimension degeneree
    carte_key                  INT NOT NULL,
    navire_key                 INT NOT NULL,
    temps_key                  INT NOT NULL,
    espece_key                 INT NOT NULL,
    technique_key              INT NOT NULL,
    capture_nombre             DOUBLE PRECISION NULL,
    capture_poids_entier_total DOUBLE PRECISION NULL,
    capture_poids_transf_total DOUBLE PRECISION NULL,
    capture_valeurxpf          DOUBLE PRECISION NULL
);

INSERT INTO FAIT_CAPTURE (capture_id, campagne_id, carte_key, navire_key,
                          temps_key, espece_key, technique_key,
                          capture_nombre, capture_poids_entier_total,
                          capture_poids_transf_total, capture_valeurxpf)
SELECT cap.capture_id,
       cap.capture_campagne_id,
       COALESCE(fca.carte_key, -1),
       COALESCE(fca.navire_key, -1),
       COALESCE(fca.temps_debut_key, -1),   -- pas de date propre a la capture
       COALESCE(de.espece_key, -1),
       COALESCE(dt.technique_key, -1),
       cap.capture_nombre, cap.capture_poids_entier_total,
       cap.capture_poids_transf_total, cap.capture_valeurxpf
FROM env_mer.capture_peche cap
LEFT JOIN FAIT_CAMPAGNE fca ON fca.campagne_id = cap.capture_campagne_id
-- Jointures null-safe. En SQL, NULL = NULL n'est pas vrai : une egalite
-- simple rejetterait les combinaisons dont un membre est NULL, alors
-- qu'elles existent bien dans la dimension, et la capture tomberait sur le
-- membre inconnu a tort. 1 086 captures ont technique ou transformation a
-- NULL ; produit et categorie_code n'en ont aucune aujourd'hui, mais la
-- meme precaution y evite une regression silencieuse au prochain chargement.
LEFT JOIN DIM_ESPECE de
       ON (de.categorie_code = cap.capture_categorie_code
           OR (de.categorie_code IS NULL AND cap.capture_categorie_code IS NULL))
      AND (de.produit = LEFT(cap.capture_produit, 400)
           OR (de.produit IS NULL AND cap.capture_produit IS NULL))
LEFT JOIN DIM_TECHNIQUE dt
       ON (dt.technique = LEFT(cap.capture_technique, 200)
           OR (dt.technique IS NULL AND cap.capture_technique IS NULL))
      AND (dt.transformation = LEFT(cap.capture_transformation, 200)
           OR (dt.transformation IS NULL AND cap.capture_transformation IS NULL));


-- Grain : un poste de depense d'une campagne. La cle primaire evite qu'un
-- rechargement double les montants.
CREATE TABLE FAIT_FRAIS (
    campagne_id   VARCHAR(255) NOT NULL,
    frais_id      VARCHAR(255) NOT NULL,
    nature_frais  VARCHAR(255) NULL,
    carte_key     INT NOT NULL,
    navire_key    INT NOT NULL,
    temps_key     INT NOT NULL,
    montant       DOUBLE PRECISION NULL,
    CONSTRAINT PK_FAIT_FRAIS PRIMARY KEY (campagne_id, frais_id)
);

INSERT INTO FAIT_FRAIS (campagne_id, frais_id, nature_frais, carte_key,
                        navire_key, temps_key, montant)
SELECT cf.campagne_id, cf.frais_id, f.libelle,
       COALESCE(fca.carte_key, -1),
       COALESCE(fca.navire_key, -1),
       COALESCE(fca.temps_debut_key, -1),
       cf.montant
FROM env_mer.campagne_frais cf
JOIN env_mer.frais f ON f.frais_id = cf.frais_id
LEFT JOIN FAIT_CAMPAGNE fca ON fca.campagne_id = cf.campagne_id;


-- 3. TABLES DE PONT ----------------------------------------------------------

-- facteur = 1/nb_zones : sans ponderation, le poids d'une capture serait
-- compte une fois par zone.
--
--   SELECT z.label, SUM(f.capture_poids_entier_total * p.facteur)
--   FROM FAIT_CAPTURE f
--   JOIN PONT_CAPTURE_ZONE p ON p.capture_id = f.capture_id
--   JOIN DIM_ZONE_PECHE   z ON z.zone_key    = p.zone_key
--   GROUP BY z.label;
--
-- Pour un total sans ventilation, interroger FAIT_CAPTURE seule.
CREATE TABLE PONT_CAPTURE_ZONE (
    capture_id VARCHAR(255) NOT NULL,
    zone_key   INT          NOT NULL,
    nb_zones   INT          NULL,
    facteur    DOUBLE PRECISION NULL,
    CONSTRAINT PK_PONT_CAPTURE_ZONE PRIMARY KEY (capture_id, zone_key)
);

INSERT INTO PONT_CAPTURE_ZONE (capture_id, zone_key, nb_zones, facteur)
SELECT cz.capture_id,
       COALESCE(z.zone_key, -1),
       n.nb,
       1.0 / n.nb
FROM (SELECT DISTINCT capture_id, zone_peche_id
      FROM env_mer.capture_zone
      WHERE zone_peche_id IS NOT NULL) cz
JOIN (SELECT capture_id, COUNT(DISTINCT zone_peche_id) AS nb
      FROM env_mer.capture_zone
      WHERE zone_peche_id IS NOT NULL
      GROUP BY capture_id) n ON n.capture_id = cz.capture_id
LEFT JOIN DIM_ZONE_PECHE z ON z.zone_peche_id = cz.zone_peche_id;


CREATE TABLE PONT_CARTE_PECHERIE (
    carte_key    INT NOT NULL,
    pecherie_key INT NOT NULL,
    CONSTRAINT PK_PONT_CARTE_PECHERIE PRIMARY KEY (carte_key, pecherie_key)
);

INSERT INTO PONT_CARTE_PECHERIE (carte_key, pecherie_key)
SELECT DISTINCT COALESCE(dc.carte_key, -1), COALESCE(dp.pecherie_key, -1)
FROM env_mer.carte_pecherie_specifique cps
LEFT JOIN DIM_CARTE    dc ON dc.carte_id = cps.carte_id
LEFT JOIN DIM_PECHERIE dp ON dp.code     = cps.code;


-- 4. INDEX -------------------------------------------------------------------

CREATE INDEX IX_FAIT_CARTE_temps      ON FAIT_CARTE (temps_key);
CREATE INDEX IX_FAIT_CARTE_navire     ON FAIT_CARTE (navire_key);
CREATE INDEX IX_FAIT_CAMPAGNE_carte   ON FAIT_CAMPAGNE (carte_key);
CREATE INDEX IX_FAIT_CAMPAGNE_temps   ON FAIT_CAMPAGNE (temps_debut_key);
CREATE INDEX IX_FAIT_CAPTURE_espece   ON FAIT_CAPTURE (espece_key);
CREATE INDEX IX_FAIT_CAPTURE_temps    ON FAIT_CAPTURE (temps_key);
CREATE INDEX IX_FAIT_CAPTURE_campagne ON FAIT_CAPTURE (campagne_id);
CREATE INDEX IX_FAIT_FRAIS_temps      ON FAIT_FRAIS (temps_key);
CREATE INDEX IX_PONT_ZONE_zone        ON PONT_CAPTURE_ZONE (zone_key);
CREATE INDEX IX_DIM_MOTEUR_navire     ON DIM_MOTEUR (navire_key);


-- 5. VERIFICATIONS -----------------------------------------------------------

SELECT 'DIM_TEMPS' AS objet, COUNT(*) AS lignes FROM DIM_TEMPS
UNION ALL SELECT 'DIM_COMMUNE',         COUNT(*) FROM DIM_COMMUNE
UNION ALL SELECT 'DIM_PERSONNE',        COUNT(*) FROM DIM_PERSONNE
UNION ALL SELECT 'DIM_CARTE',           COUNT(*) FROM DIM_CARTE
UNION ALL SELECT 'DIM_NAVIRE',          COUNT(*) FROM DIM_NAVIRE
UNION ALL SELECT 'DIM_MOTEUR',          COUNT(*) FROM DIM_MOTEUR
UNION ALL SELECT 'DIM_ESPECE',          COUNT(*) FROM DIM_ESPECE
UNION ALL SELECT 'DIM_TECHNIQUE',       COUNT(*) FROM DIM_TECHNIQUE
UNION ALL SELECT 'DIM_ZONE_PECHE',      COUNT(*) FROM DIM_ZONE_PECHE
UNION ALL SELECT 'DIM_CARROYAGE',       COUNT(*) FROM DIM_CARROYAGE
UNION ALL SELECT 'DIM_PECHERIE',        COUNT(*) FROM DIM_PECHERIE
UNION ALL SELECT 'FAIT_CARTE',          COUNT(*) FROM FAIT_CARTE
UNION ALL SELECT 'FAIT_CAMPAGNE',       COUNT(*) FROM FAIT_CAMPAGNE
UNION ALL SELECT 'FAIT_CAPTURE',        COUNT(*) FROM FAIT_CAPTURE
UNION ALL SELECT 'FAIT_FRAIS',          COUNT(*) FROM FAIT_FRAIS
UNION ALL SELECT 'PONT_CAPTURE_ZONE',   COUNT(*) FROM PONT_CAPTURE_ZONE
UNION ALL SELECT 'PONT_CARTE_PECHERIE', COUNT(*) FROM PONT_CARTE_PECHERIE
ORDER BY objet;

-- Quelques -1 sont normaux ; un taux eleve signale une jointure ratee.
SELECT 'FAIT_CAMPAGNE.carte_key = -1' AS controle,
       SUM(CASE WHEN carte_key = -1 THEN 1 ELSE 0 END) AS inconnus,
       COUNT(*) AS total FROM FAIT_CAMPAGNE
UNION ALL
SELECT 'FAIT_CAPTURE.espece_key = -1',
       SUM(CASE WHEN espece_key = -1 THEN 1 ELSE 0 END), COUNT(*) FROM FAIT_CAPTURE
UNION ALL
SELECT 'FAIT_CAPTURE.technique_key = -1',
       SUM(CASE WHEN technique_key = -1 THEN 1 ELSE 0 END), COUNT(*) FROM FAIT_CAPTURE
UNION ALL
SELECT 'FAIT_CAMPAGNE.temps_debut_key = -1',
       SUM(CASE WHEN temps_debut_key = -1 THEN 1 ELSE 0 END), COUNT(*) FROM FAIT_CAMPAGNE;

-- Une capture dont la technique existe en dimension ne doit pas tomber sur le
-- membre inconnu : ce controle attrape une jointure redevenue non null-safe.
SELECT COUNT(*) AS captures_mal_rattachees
FROM FAIT_CAPTURE f
JOIN env_mer.capture_peche s ON s.capture_id = f.capture_id
WHERE f.technique_key = -1
  AND EXISTS (SELECT 1 FROM DIM_TECHNIQUE d
              WHERE (d.technique = LEFT(s.capture_technique, 200)
                     OR (d.technique IS NULL AND s.capture_technique IS NULL))
                AND (d.transformation = LEFT(s.capture_transformation, 200)
                     OR (d.transformation IS NULL AND s.capture_transformation IS NULL)));

-- Le grain de DIM_PERSONNE doit etre strictement la personne.
SELECT COUNT(*) AS personnes_en_double
FROM (SELECT personne_id FROM DIM_PERSONNE WHERE personne_id IS NOT NULL
      GROUP BY personne_id HAVING COUNT(*) > 1) x;

-- La somme des facteurs doit valoir 1 pour chaque capture ventilee.
SELECT COUNT(*) AS captures_mal_reparties
FROM (SELECT capture_id, SUM(facteur) AS s
      FROM PONT_CAPTURE_ZONE GROUP BY capture_id) x
WHERE ABS(x.s - 1.0) > 0.000001;

-- FAIT_CARTE etant un agregat, sa recette doit rester proche de la somme des
-- campagnes de la meme carte.
SELECT COUNT(*) AS cartes_en_ecart
FROM FAIT_CARTE fc
JOIN (SELECT carte_key, SUM(campagne_recette) AS recette
      FROM FAIT_CAMPAGNE GROUP BY carte_key) ca ON ca.carte_key = fc.carte_key
WHERE ABS(COALESCE(fc.carte_recette,0) - COALESCE(ca.recette,0)) > 1;
